import = [
"~/.config/alacritty/themes/gruvbox_dark.toml",
# "~/.config/alacritty/themes/gruvbox_light.toml",
# "~/.config/alacritty/themes/gruvbox_material.toml",
# "~/.config/alacritty/themes/gruvbox_material_medium_dark.toml",
# "~/.config/alacritty/themes/gruvbox_material_medium_light.toml",
]


[window]
padding = { x = 3, y = 3 }


[font]
normal = { family = "JetBrains Mono", style = "Regular" }
bold = { family = "JetBrains Mono", style = "Bold" }
italic = { family = "JetBrains Mono", style = "Italic" }
bold_italic = { family = "JetBrains Mono", style = "Bold Italic" }
size = 7.5
